version: '3.1'

services:
  db:
    image: postgres:latest
    container_name: springboot-postgres
    environment:
      POSTGRES_DB: prueba
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
    ports:
      - "5432:5432"